from .SelectLatentSize import SLS_CLASS_MAPPINGS, SLS_NAME_MAPPINGS
from .TextEncode3in1 import TE3_CLASS_MAPPINGS, TE3_NAME_MAPPINGS
from .SamplerWithVae import SWV_CLASS_MAPPINGS, SWV_NAME_MAPPINGS
from .UpscaleByN import UBN_CLASS_MAPPINGS, UBN_NAME_MAPPINGS
from .newLatentAdvanced import newLatentAdvanced

# NODE_CLASS_MAPPINGS = {}
# NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS = {
    "newLatentAdvanced": newLatentAdvanced,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "newLatentAdvanced": "Select new latent image Advanced",
}

NODE_CLASS_MAPPINGS.update(SLS_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(SLS_NAME_MAPPINGS)

NODE_CLASS_MAPPINGS.update(TE3_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(TE3_NAME_MAPPINGS)

NODE_CLASS_MAPPINGS.update(SWV_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(SWV_NAME_MAPPINGS)

NODE_CLASS_MAPPINGS.update(UBN_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(UBN_NAME_MAPPINGS)

# NODE_CLASS_MAPPINGS.update(NLA_CLASS_MAPPINGS)
# NODE_DISPLAY_NAME_MAPPINGS.update(NLA_NAME_MAPPINGS)

WEB_DIRECTORY = "./js"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]