from .SelectLatentSize import SLS_CLASS_MAPPINGS, SLS_NAME_MAPPINGS
from .TextEncode3in1 import TE3_CLASS_MAPPINGS, TE3_NAME_MAPPINGS
from .SamplerWithVae import SWV_CLASS_MAPPINGS, SWV_NAME_MAPPINGS
from .UpscaleByN import UBN_CLASS_MAPPINGS, UBN_NAME_MAPPINGS
from .LMStudioApi import LMS_CLASS_MAPPINGS, LMS_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(SLS_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(SLS_NAME_MAPPINGS)

NODE_CLASS_MAPPINGS.update(TE3_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(TE3_NAME_MAPPINGS)

NODE_CLASS_MAPPINGS.update(SWV_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(SWV_NAME_MAPPINGS)

NODE_CLASS_MAPPINGS.update(UBN_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(UBN_NAME_MAPPINGS)

NODE_CLASS_MAPPINGS.update(LMS_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(LMS_NAME_MAPPINGS)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]